version: "3"

services:
  minecraft:
    image: 08d7f9d336b0
    volumes:
      - minecraftdata:/minecraft/data
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    tty: true
    stdin_open: true	
    restart: unless-stopped
volumes:
  minecraftdata:
    external: true
